### ISSUE TITLE
Trouble setting remote

### ISSUE THREAD

**Issue by courtneytkacz** [courtneytkacz/vmfa-digcoll-map#1]
@chrisdaaz  Copying, pasting, and lightly editing messages from Moodle so we can more easily discuss here, as suggested.

**January 19
Courtney Tkacz**
Hi Chris - I'm having trouble with my final project. As you suggested, I forked the Bayou City DAMS repo then cloned it to my computer. I've made changes to the index file, which I committed locally, but I can't seem to push them to the repo. At first it said I hadn't configured the local repo (which I hadn't). I don't think I did it correctly though since I can't push without getting an error.

Here's what I did and the messages I'm receiving:

courtneytkacz@Courtneys-iMac vmfa-digcoll-map % git remote add origin git@github.com:courtneyktacz/vmfa-digcoll-map.git
courtneytkacz@Courtneys-iMac vmfa-digcoll-map % git branch -M main
courtneytkacz@Courtneys-iMac vmfa-digcoll-map % git push -u origin main
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
courtneytkacz@Courtneys-iMac vmfa-digcoll-map % git remote add origin git@github.com:courtneytkacz/vmfa-digcoll-map.git
fatal: remote origin already exists.
courtneytkacz@Courtneys-iMac vmfa-digcoll-map % git push
fatal: The current branch main has no upstream branch.
To push the current branch and set the remote as upstream, use

git push --set-upstream origin main

courtneytkacz@Courtneys-iMac vmfa-digcoll-map % git push --set-upstream origin main
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**January 20
Chris Diaz**
Ahhh interesting. I'm seeing a few things here. First, can you go to the Settings of your repository and enable Issues? It will be much easier for us to discuss your project there than moodle. Instructions here: https://softwareengineering.stackexchange.com/a/179470

Next, can you run the `$ git remote -v ` to make sure your origin is set to: `git@github.com:courtneytkacz/vmfa-digcoll-map.git`

Lastly, the bayoucity dams reposit does NOT use a `main` branch, interestingly. Their default branch is actually called `gh-pages` which is a special branch on GitHub that will trigger website builds.

If you're authenticating to github with SSH, you should see this after running `$ git remote -v `: origin git@github.com:courtneytkacz/vmfa-digcoll-map.git (fetch)
origin git@github.com:courtneytkacz/vmfa-digcoll-map.git (push)

if you see HTTPS (https://github.com/courtneytkacz/vmfa-digcoll-map.git), then you might change the URL from HTTPS to SSH: https://docs.github.com/en/github/using-git/changing-a-remotes-url#switching-remote-urls-from-https-to-ssh

if you see something that doesn't look correct when you run `$ git remote -v`, then you might need to remove and reset your origin remote:

$ git remote rm origin
$ git remote add origin git@github.com:courtneytkacz/vmfa-digcoll-map.git

then you can just do `git push` and git will push your current branch to the corresponding branch on github.

**Comment by courtneytkacz** [comment]
@chrisdaaz 

I did everything you suggested above, and am authenticating with SSH and my origin is set correctly. But I'm getting the same error as before: 

courtneytkacz@Courtneys-iMac vmfa-digcoll-map % git remote -v
origin  git@github.com:courtneyktacz/vmfa-digcoll-map.git (fetch)
origin  git@github.com:courtneyktacz/vmfa-digcoll-map.git (push)
courtneytkacz@Courtneys-iMac vmfa-digcoll-map % git push
fatal: The current branch main has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin main

I tried different push commands, and those had errors too:

courtneytkacz@Courtneys-iMac vmfa-digcoll-map % git push origin gh-pages
error: src refspec gh-pages does not match any
error: failed to push some refs to 'git@github.com:courtneyktacz/vmfa-digcoll-map.git'

courtneytkacz@Courtneys-iMac vmfa-digcoll-map % git push origin main
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Is my syntax wrong? Or do you think it's because, as you noted, the default branch is called gh-pages and not main? Should I rename the branch to main?

**Comment by chrisdaaz** [comment]
@courtneytkacz 

Yes, I think it might have to do with the branch names. I think first, we should see which branches you have locally:

```
$ git branch
```

By my reading, I would expect you to see this response `* main`. In which case, I recommend renaming the `main` branch to match the default branch on github:

```
$ git branch -m gh-pages
```

Then I think doing `$ git push` will work.

**Comment by courtneytkacz** [comment]
I see main and gh-pages:

<img width="436" alt="Screen Shot 2021-01-22 at 12 00 44 PM" src="https://user-images.githubusercontent.com/77212128/105521131-81181680-5ca9-11eb-979f-5dc4e8b2334e.png">

**Comment by chrisdaaz** [comment]
OK. The error you're seeing is due to `main` not being a branch that is on github. To push a new branch to github, you need to push it explicitly (`git push origin main`). Once the branch exists locally and on your remote (i.e. Github), you can run `git push` and git will that you want to push the commits from your current branch to the corresponding branch on github. 

The default branch of this repository is `gh-pages` (this sometimes happens when adapting other people's git projects, wherein `main` is not the default branch). All of your commits should be made to `gh-pages`.

If you have commits on your `main` branch that you want in the `gh-pages` branch, you'll want to merge those commits into the `gh-pages` branch locally, then push the `gh-pages` branch to github:

```
git checkout gh-pages
git merge main
git push
```

If you don't have any commits on `main` that you want in your project, you can just switch to the `gh-pages` branch and commit directly to it. You can delete `main` if you no longer need it.

```
git checkout gh-pages
git branch -d main
```

If you decide to push the `main` branch to github, you can do so with this command `git push origin main`. Then, if you want the commits from `main` to be merged into `gh-pages`, you can make a pull request from `main` to `gh-pages` in GitHub.

Message me on Moodle if you'd prefer to set up a quick phone or video call to talk through this. I have some time later today or next week.

**Comment by courtneytkacz** [comment]
Your message made perfect sense, but I'm still stuck. At this point, I'm ready to scrap it and start over as I haven't made many edits. In either case, I'll message you on Moodle to schedule a time to talk next week. Sorry! Here's what I'm seeing:

<img width="509" alt="Screen Shot 2021-01-22 at 8 57 00 PM" src="https://user-images.githubusercontent.com/77212128/105565381-7d5db180-5cf4-11eb-8760-70f03bf1ed36.png">

**Comment by chrisdaaz** [comment]
> At this point, I'm ready to scrap it and start over

That is *always* an option! I've definitely done that over the years. A few strategies for starting over:

- If you know that there's nothing in your local repository you need. You can delete the folder on your computer (as if it were any other folder) and clone the repository again.

- If you felt the need to save any work in your local repository, but needed to exit out of what is sometimes called "git hell," you can copy the files you need to a "safe" temporary location (e.g. the Desktop), delete the folder, clone the repository again, and re-add the files to the repository. From there, you can commit them and be on your way.

Another piece of advice, since you're the primary contributor, you can do all of your commits on the `gh-pages` branch without ever needing to make new branches. If you get collaborators, you can make them contribute via branches or forks, while continuing to work from `gh-pages`.

**Comment by courtneytkacz** [comment]
Before scraping, I renamed the branch to "main" in the repo settings to see if that cleared things up. Then GitHub helpfully told me to do this: 

<img width="504" alt="Screen Shot 2021-01-25 at 3 17 52 PM" src="https://user-images.githubusercontent.com/77212128/105761698-6ea81200-5f21-11eb-8ee7-52374ea1a7ce.png">

However, I am still getting the access issues, so I'm going to start over: 

<img width="559" alt="Screen Shot 2021-01-25 at 3 19 38 PM" src="https://user-images.githubusercontent.com/77212128/105761729-7962a700-5f21-11eb-885d-fc49e889112e.png">

Since the branch has been renamed before cloning, hopefully things will go smoother.

**Comment by chrisdaaz** [comment]
I found this page explaining the error (just FYI): https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/error-repository-not-found

**Comment by courtneytkacz** [comment]
I started over and all is well! Thanks for walking me through all of the issues.
