### ISSUE TITLE
Problem Deleting Folder from Forked Repository

### ISSUE THREAD

**Issue by courtneytkacz** [courtneytkacz/vmfa-digcoll-map#6]
@chrisdaaz 

I noticed that there is a folder in the repo I forked called "migration" which has records of digitized items from the Bayou City DAMS (I assume). I deleted the folder locally and tried to push the deletion upstream, but received this error:

<img width="722" alt="Screen Shot 2021-01-29 at 1 06 33 AM" src="https://user-images.githubusercontent.com/77212128/106238507-fb2b2c80-61ce-11eb-9b63-a718f7fcb3b2.png">

**Comment by chrisdaaz** [comment]
hello! i tried to address this in https://github.com/courtneytkacz/vmfa-digcoll-map/commit/0ac12cd528640ac8867cc0f8635432e397cf1821

what i think happened was that removing files from a git repository require special commands to remove them from the history:

- `git rm` followed by a file name (with extension) will remove a file from the git history (eg. `git rm README.md`)
- `git rm -r` followed by the name of a directory will remove an entire folder from the git historu (e.g. `git rm -r migration`)

I did this in https://github.com/courtneytkacz/vmfa-digcoll-map/commit/0ac12cd528640ac8867cc0f8635432e397cf1821

```
git rm -r migration
git commit -m "delete migration folder"
git push origin main
```

deleting folders the normal way (via the file explorer / moving files to the trash) can cause errors in git because that change happened without the proper git loggin operations (i.e. staging changes, commiting changes, etc.).

when you refresh your local repository (`git pull origin main`) and run `git status`, you will hopefully see a message that looks like this: 

```
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```

if you see the list of deleted files from the `migration` folder (even though you deleted them from your computer already), you may need to remove the files from your git cache, with this command:

```
git rm -r --cached migration
```

there are some ways with [dealing with this scenario here](https://stackoverflow.com/questions/6313126/how-to-remove-a-directory-from-git-repository) if you're seeing more errors.

**Comment by courtneytkacz** [comment]
That worked great, and makes perfect sense. It will definitely take time to remember to put on my "git brain" to perform tasks!
